### PR TITLE
Only allow strings when by_value is False

### LINKED ISSUE #6: Fails if input data type is not string
When not using "by_value", the schema expects the enum to be of string type.

If the value is of different type, it does not detect error (like "Value must be of type str"), but it fails.

Following test case:

```python
from marshmallow import Schema, fields
from marshmallow_enum import EnumField
from enum import Enum


class SexEnum(Enum):
    male = 0
    female = 1


class SexyUserSchema(Schema):
    username = fields.String(required=True)
    sex = EnumField(SexEnum,
                    required=True,
                    error="{input} must be  one of {choices}")


def test_enum_wrong_type():
    user_schema = SexyUserSchema()

    indata = dict(username="jan", sex=324)

    res = user_schema.load(indata)
    print(res)
    assert res.errors
```

fails:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    def test_enum_wrong_type():
        user_schema = SexyUserSchema()

        indata = dict(username="jan", sex=324)

>       res = user_schema.load(indata)

tests/test_enum_attnostring.py:23:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py36/lib/python3.6/site-packages/marshmallow/schema.py:580: in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
.tox/py36/lib/python3.6/site-packages/marshmallow/schema.py:660: in _do_load
    index_errors=self.opts.index_errors,
.tox/py36/lib/python3.6/site-packages/marshmallow/marshalling.py:295: in deserialize
    index=(index if index_errors else None)
.tox/py36/lib/python3.6/site-packages/marshmallow/marshalling.py:68: in call_and_store
    value = getter_func(data)
.tox/py36/lib/python3.6/site-packages/marshmallow/marshalling.py:288: in <lambda>
    data
.tox/py36/lib/python3.6/site-packages/marshmallow/fields.py:265: in deserialize
    output = self._deserialize(value, attr, data)
.tox/py36/lib/python3.6/site-packages/marshmallow_enum/__init__.py:31: in _deserialize
    return self._deserialize_by_name(value, attr, data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fields.EnumField(default=<marshmallow.missing>, attribute=None, validate=None, required=True, lo
ad_only=False, dump_o...idator_failed': 'Invalid value.', 'by_name': 'Invalid enum member {input}', 'by_
value': 'Invalid enum value {input}'})>
value = 324, attr = 'sex', data = {'sex': 324, 'username': 'jan'}

    def _deserialize_by_name(self, value, attr, data):
        try:
>           return getattr(self.enum, value)
E           TypeError: getattr(): attribute name must be string

.tox/py36/lib/python3.6/site-packages/marshmallow_enum/__init__.py:41: TypeError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/javl/sandbox/playwith_marshmallow/.tox/py36/lib/python3.6/site-packages/marshmallow_enum/__init_
_.py(41)_deserialize_by_name()
-> return getattr(self.enum, value)
```

### PR DESCRIPTION
**Pull request by justanr**
Closes #6 

@vlcinsky does this properly address your issue?

### CODE REVIEW

**Comment by vlcinsky** [comment]
Well done @justanr, now it properly reports the problem that the value shall be of type string.

Anyway, if I pass custom error message "{input} must be  one of {choices}" it fails on format as "input" key is not present in format arguments.
If you want to test it, run my test case from issue #6 which is using such custom message.

I see two possible approaches:
1. if custom error message is present, use it as it is (and pass in all required keys not to fail)
2. In case of lower level errors (as "value shall be string"), ignore custom error message and use just the lower level one. So instead of custom error like "your waltz steps shall go in triples" there would be message "muddy shoes not allowed in this ballroom"

**Comment by justanr** [comment]
That's a good point, the call to fail doesn't pass any extra arguments but it should. I'll fix that when I get home tonight.

**Comment by justanr** [comment]
@vlcinsky The fail call is passing the `{input}` parameter now. `{name}` and `{value}` aren't supported any more.

**Comment by justanr** [comment]
@vlcinsky Any more feedback on this?

**Comment by vlcinsky** [comment]
@justanr the latest commit is passing my tests so it seems fine.

For a moment I have wondered, why the line 48 in `__init__.py` has only `input` key but not the `choices`. Anyway, the test is passing even with a pattern including `choices` so it works well. The `.fail()` methods handles that properly.

In summary: all seems to be resolved. Well done.

**Comment by justanr** [comment]
@vlcinsky The field translates to input under the hood, I need do some detecting if the deprecated format options are provided and issue a warning. Choices is drawn from the enum itself depending on if it is processing via value or name.

Another feature I keep meaning to get around to is supporting loading from one and dumping to another. e.g. you expect users to send you `Foo` but internally you pull `1` from the database.

At any rate, I'll merge this and issue a new release since it sounds like you're using this and installing from github is janky at best.

**Comment by justanr** [comment]
Alright 1.3 is pushed to pypi and tagged on github, let me know if you find anything else!

**Comment by vlcinsky** [comment]
Thanks. Tested against version 1.3 on pypi.python.org and all works fine.
Thanks for pushing the version to pypi, it makes deployment simpler.
Anyway, since I installed private pypi server based on devpi, testing development versions from various sources is real fun (pull your ISSUE-6 branch, run `$ devpi upload` into my /javl/dev pypi index and run tox tasks installing from this index automatically as I used `$ devpi use javl/dev --set-cfg` what reconfigured pip to use my new index). It is off-topic, but I had to share it.

Regarding the `Foo` and pulling from database - I am not sure I completely understand it, but it sounds interesting. Something like handling enums based on enumeration values stored in a database.

**Pull request merged**
